{
 "title": "KVDB(Redis/KVRocks)",
 "description": "KVDB Sentinel Exporter is a tool for monitoring Redis Sentinel.",
 "tags": [
  "redis",
  "kvrocks",
  "redis-sentinel"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "sentinelName",
    "label": "Sentinel",
    "query": {
     "query": "label_values(kvdb_up{}, sentinel_name)"
    }
   },
   {
    "name": "groupName",
    "label": "Group",
    "query": {
     "query": "label_values(kvdb_up{sentinel_name=\"$sentinelName\"}, group_name)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kvdb_up{sentinel_name=\"$sentinelName\",group_name=\"$groupName\"}, db_instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instance Summarize", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Summarize",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (sentinel_name, db_instance, group_name)(kvdb_uptime_in_seconds{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (sentinel_name,db_instance, group_name)(kvdb_version{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (sentinel_name,db_instance, group_name)(kvdb_connected_clients{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (sentinel_name,db_instance, group_name)(kvdb_port{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (sentinel_name,db_instance, group_name)(kvdb_role{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (sentinel_name,db_instance, group_name)(kvdb_instantaneous_ops_per_sec{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (sentinel_name,db_instance, group_name)(kvdb_net_input_kbps{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (sentinel_name,db_instance, group_name)(kvdb_net_output_kbps{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (sentinel_name,db_instance, group_name)(kvdb_memory_used_bytes{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (sentinel_name,db_instance, group_name)(kvdb_engine_type{})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Instance Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(kvdb_uptime_in_seconds{db_instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kvdb_version{db_instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kvdb_role{db_instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (kvdb_memory_used_bytes{db_instance=~\"$instance\"}  / kvdb_memory_max_bytes{db_instance=~\"$instance\"} )"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kvdb_instantaneous_ops_per_sec{db_instance=~\"$instance\"}",
     "legendFormat": "realtime qps"
    },
    {
     "expr": "rate(kvdb_commands_processed_total{db_instance=~\"$instance\"}[1m])",
     "legendFormat": "rate qps"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kvdb_connected_clients{db_instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Port",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kvdb_port{db_instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Realtime Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "kvdb_net_input_kbps{db_instance=~\"$instance\"}",
     "legendFormat": "IN"
    },
    {
     "expr": "kvdb_net_output_kbps{db_instance=~\"$instance\"}",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Rate Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kvdb_net_input_bytes_total{db_instance=~\"$instance\"}[5m])",
     "legendFormat": "IN"
    },
    {
     "expr": "rate(kvdb_net_output_bytes_total{db_instance=~\"$instance\"}[5m])",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kvdb_memory_used_bytes{db_instance=~\"$instance\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "kvdb_memory_max_bytes{db_instance=~\"$instance\"} ",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(8, irate(kvdb_commands_total{db_instance=~\"$instance\"} [1m]))",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (kvdb_db_keys{db_instance=~\"$instance\"}) by (db)",
     "legendFormat": "{{ db }} - total"
    },
    {
     "expr": "sum (kvdb_db_keys_expiring{db_instance=~\"$instance\"}) by (db)",
     "legendFormat": "{{ db }} - expire"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kvdb_db_keys{db_instance=~\"$instance\"}) - sum (kvdb_db_keys_expiring{db_instance=~\"$instance\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (kvdb_db_keys_expiring{db_instance=~\"$instance\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Redis connected clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kvdb_connected_clients{db_instance=\"$instance\"}",
     "legendFormat": "connected"
    },
    {
     "expr": "kvdb_max_clients{db_instance=\"$instance\"}",
     "legendFormat": "max"
    },
    {
     "expr": "kvdb_blocked_clients{db_instance=\"$instance\"}",
     "legendFormat": "blocked"
    }
   ]
  }
 ]
}